### ISSUE TITLE
Problems with install or migrate especially pgcrypto

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-authentication-service#1381]
The challenges:

- The database "migration" actually seems to be the database initialization or a regular update.
When I read the documentation this was not clear. I wanted to start plain and not migrate a system.
- When I started the database migration, I got the error message about the missing crypto module.
- The idea is good that the migration seems to try to install the module itself. But for this admin rights are necessary. A normal database user does not have them.
- Then I installed the module myself. Unfortunately, the migration cannot be completed then either, as it does not seem to detect that the module is already present.

So it seems that the installation and use is only possible with an database admin user.

```console
2023-07-20T15:00:04.226549Z  INFO cli.database.migrate:db.migrate: sqlx::postgres::notice: relation "_sqlx_migrations" already exists, skipping
Error: could not run migrations

Caused by:
    0: while executing migrations: error returned from database: permission denied to create extension "pgcrypto"
    1: error returned from database: permission denied to create extension "pgcrypto"
    2: permission denied to create extension "pgcrypto"
```

**Comment by sandhose** [comment]
> The database "migration" actually seems to be the database initialization or a regular update.
When I read the documentation this was not clear. I wanted to start plain and not migrate a system.

You're right, "database schema upgrade" or something similar might be clearer. Please note that the tools to migrate an existing Synapse homeserver database are not yet part of this project, so in its current state it is only suitable for new homeserver deployments. We do have an internal tool to migrate existing hosts that we plan to release when we're confortable enough with its reliability, which should be quite soon now

> The idea is good that the migration seems to try to install the module itself. But for this admin rights are necessary. A normal database user does not have them.

This is quite surprising to me. The module documentation state:
> *This module is considered “trusted”, that is, it can be installed by non-superusers who have CREATE privilege on the current database.*

Are you running a custom version of postgres that does not have the extension marked as trusted? Is the user the owner of the database?
Whether the extension is trusted or not should be visible in the extension control file: there should be a `trusted = true` line in `<prefix>/share/extension/pgcrypto.control`

> Then I installed the module myself. Unfortunately, the migration cannot be completed then either, as it does not seem to detect that the module is already present.

I assume this is because the migration will always try to run the `CREATE EXTENSION IF NOT EXISTS`, which might go through the permissions check even if the extension is already loaded?
