### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by weeman1337** [matrix-org/matrix-authentication-service#1906]
Steps to reproduce the issue:
- Open Element Desktop
- Enter your username
- It says „Go to your browser to complete Sign In“ and opens a browser window
- Log in with your account
- It asks „„element://vector/webapp/ wants to access your account.““
- Click „Continue“ 

Expected:
- Now logged in

What happens:
- Nothing

If you click „Continue“ again you get this message:

```
Unexpected error
Invalid database operation
RepositoryError { source: InvalidOperation { source: Some(InvalidTransitionError) } }
```

Environment:
- Element Desktop Nightly (09.10.2023)
- Firefox 118.0.1
- Ubuntu 22.04.3 LTS
- Homeserver: `element.io`

**Comment by sandhose** [comment]
When you're getting back to the client, it does it with a "303 See Other" redirect to the client redirect URI (so in your case, `element://vector/webapp/?loginToken=xxyyzz`) 

This feels like Firefox fails to open the native URL link. I can't reproduce with Firefox on macOS, which makes me wonder two things:

 - what OS are you on? This would be useful for me to try and reproduce the issue.
 - can you reproduce with an SSO login on another non-OIDC homeserver (like using a social account on matrix.org)? This would be useful since the old Synapse client redirect works with a link in a web page, not a redirect

**Comment by weeman1337** [comment]
Added the OS. It seems to be an issue with Element Desktop. It doesn't register for the element:// file type.

**Comment by weeman1337** [comment]
Hard-wired Fireofx to open `element://` with Element Desktop. It does now work.

Seems to be a Element Desktop issue.
