### ISSUE TITLE
Generate config file (not output) with `mas-cli config generate`

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-authentication-service#2046]
It is recommended to create secrets and default config with 
`mas-cli config generate > config.yaml` ([docs](https://matrix-org.github.io/matrix-authentication-service/setup/general.html#initial-configuration-generation)).

This works with shell, bash or similar tools and `docker run`.

In a kubernates only deployment it is not possible to create the config file.
Create the config file (`> config.yaml`) is part of the functional scope of a shell. The [distroless container](https://github.com/matrix-org/matrix-authentication-service/blob/464eeda3f3c4bb03b8e5cae51f42c1b1945bfbde/Dockerfile#L177) has no shell and cannot create the file.

IMO  it would be good if `mas-cli` wrote the file itself.

**Comment by sandhose** [comment]
That makes sense! If one would implement such feature, they would:

 - add a flag on the config dump/generate commands [here](https://github.com/matrix-org/matrix-authentication-service/blob/520357e78b6b3d0ef517350259fe240d82d3e2b1/crates/cli/src/commands/config.rs#L105-L111) ([here](https://github.com/matrix-org/matrix-authentication-service/blob/520357e78b6b3d0ef517350259fe240d82d3e2b1/crates/cli/src/commands/mod.rs#L54-L56) is in an example of option where a file is being passed)
 - open that file and write to it [here](https://github.com/matrix-org/matrix-authentication-service/blob/main/crates/cli/src/commands/config.rs#L152) instead of stdout, if provided

If you need a shell in the container, please note that there is a `-debug` variant that has the busybox tools installed,
